# 配置编译语言以及需要的版本
language: node_js
node_js:
  - lts/*

# 配置监听的分支，这里配置 hexo 分支，也就是监听源文件的改动
branches:
  only:
    - hexo

# 配置缓存，加快部署时间
#cache
cache:
  apt: true
  directories:
    - "node_modules"


before_install:
  # 更改时区，不然默认提交时间是 UTC 标准时间
  - export TZ='Asia/Shanghai'
  # 部署环境安装 hexo
  - npm install -g hexo-cli

install:
  # 安装依赖
  - npm install

script:
  - hexo clean
  - hexo generate

## 部署方式二，网上大多数人采用的是这种方式部署
after_script:
  - git clone ${GH_REF_SSH} .deploy_git #先拉取项目，取得历史提交记录
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/  ## 拷贝历史 commit 记录，不然每次构建都是全新的环境，造成历史 commit 记录被清空
  - cd ./public
  - git config user.name "mumudm"
  - git config user.email "liangpengjiedm@gmail.com"
  - git add .
  - git commit -m "Site updated `date +"%Y-%m-%d %H:%M"`. auto deploy by TravisCI 0。0"
  # Github Pages
  - git push  --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master


## 变量
env:
  global:
    - GH_REF: github.com/mumudm/mumudm.github.io
    - GH_REF_SSH: git@github.com:mumudm/mumudm.github.io.git